AWSTemplateFormatVersion: 2010-09-09

Description: ECS CX Interview Questions Scenario 2 Template 2

Transform: AWS::Serverless-2016-10-31

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Lambda configuration
        Parameters:
          - pArtifactS3Key
          - pLogLevel
    ParameterLabels:
      pArtifactS3Key:
        default: What is the file name of the source code?
      pLogLevel:
        default: What level of logging for the Lambda?

Parameters:
  pArtifactS3Key:
    AllowedPattern: ^[0-9a-zA-Z-\/\.]*$
    ConstraintDescription: key can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/). It cannot start or end
      with forward slash (/) because they are automatically appended.
    Description: S3 key for the Lambda zipfile. key
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/). It cannot start or end with forward slash (/) because they
      are automatically appended.
    Type: String
    Default: GetItemDynamoDbLambda.zip

  pLogLevel:
    Description: verbosity level of function loggers
    Type: String
    Default: DEBUG
    AllowedValues:
      - CRITICAL
      - ERROR
      - WARNING
      - INFO
      - DEBUG

Resources:

  rGetCustomerInformationAppFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      # Add policy to read dynamodb
      Policies:
        - PolicyName: allow-dynamodb-read
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - 'dynamodb:BatchGetItem'
                - 'dynamodb:Describe*'
                - 'dynamodb:List*'
                - 'dynamodb:GetItem'
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                Resource: !GetAtt rCustomerInformationDynamoDb.Arn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # Complete Lambda resource based on requirements
  rGetCustomerInformationAppFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      AutoPublishAlias: GetCustomerInformationAppFunctionRole
      Handler: get_item.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          LOG_LEVEL: !Ref pLogLevel
          TABLE_NAME: CustomerInfoTable
          TABLE_REGION: !Ref AWS::Region
      CodeUri:
        Bucket:   
            Fn::ImportValue: S3BucketName
        Key: !Ref pArtifactS3Key
      Role: !GetAtt rCustomerInformationDynamoDb.Arn
      DeploymentPreference:
        Type: AllAtOnce
      Timeout: 10

  # Complete DynamoDb resource for string attribute "PhoneNumber"
  rCustomerInformationDynamoDb:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PhoneNumber
          AttributeType: S
      KeySchema:
        - AttributeName: PhoneNumber
          KeyType: HASH
      TableName: CustomerInfoTable

Outputs:

  GetCustomerInformationAppFunctionRole:
    Description: IAM function role Arn for the Get Customer Information App Function
    Value: !Ref rGetCustomerInformationAppFunctionRole

  GetCustomerInformationLambdaFunction:
    Description: Arn of Get Customer information Lambda Function
    Value: !Ref rGetCustomerInformationAppFunction

  CustomerInformationDynamoDb:
    Description: Customer Information Dynamo DB Table name
    Value: !GetAtt rCustomerInformationDynamoDb.Arn
